[package]
name = "dll"
version = "0.1.0"
authors = ["Sebastian"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3", features = ["winuser", "consoleapi", "synchapi", "xinput", "impl-default"] }

[build-dependencies]
cc = "1.0"
